Radu:
- 0.008535502478480339
- -0.015355951152741909
- 0.0014608359197154641
- 0.08193997293710709
- 0.11287994682788849
- 0.05441921204328537
- -0.04761313647031784
- -0.0018652476137503982
- 0.045234911143779755
- -0.02702803537249565
- 0.046508874744176865
- -0.04485024884343147
- -0.02211044915020466
- 0.0390053428709507
- 0.060013383626937866
- -0.03230251371860504
- 0.0031168677378445864
- 0.0989004522562027
- 0.015009063296020031
- 0.012514309957623482
- -0.05807872116565704
- 0.021385803818702698
- 0.028670789673924446
- -0.012539512477815151
- -0.049133095890283585
- 0.08103694766759872
- 0.0105877835303545
- 0.019843365997076035
- 0.06363653391599655
- -0.0006998541066423059
- -0.06909520924091339
- -0.012732991948723793
- -0.018955238163471222
- -0.026241108775138855
- 0.07272645831108093
- 0.040399957448244095
- 0.059431664645671844
- -0.0011658451985567808
- -0.007232069503515959
- 0.0662330836057663
- -0.025917217135429382
- 0.06943824142217636
- -0.056806035339832306
- -0.06624268740415573
- 0.019333545118570328
- -0.07531066983938217
- 0.04186894744634628
- 0.04049642011523247
- -0.027576332911849022
- -0.006485503166913986
- -0.022067243233323097
- 0.018417183309793472
- -0.04413406923413277
- 0.01902945712208748
- -0.05770566314458847
- 0.01976832188665867
- -0.030575396493077278
- -0.006614958867430687
- -0.0037126096431165934
- -0.04702875390648842
- 0.0598989836871624
- -0.004310716409236193
- -0.039940137416124344
- -0.07365695387125015
- -0.0044690147042274475
- -0.022840548306703568
- 0.03779307007789612
- 0.00466585997492075
- 0.01712936721742153
- -0.0005510608898475766
- 0.01571214571595192
- 0.05496693402528763
- -0.08593446016311646
- -0.07673192769289017
- 0.0577077679336071
- -0.060571275651454926
- 0.04996119439601898
- 0.03695503622293472
- -0.04470184072852135
- -0.03011416271328926
- 0.019875647500157356
- 0.060338154435157776
- 0.03358863294124603
- 0.029600581154227257
- 0.02536061219871044
- 0.07040409743785858
- 0.06922928243875504
- 0.05014810711145401
- -0.03362173214554787
- 0.05355657637119293
- 0.04480999335646629
- -0.06605924665927887
- 0.031561676412820816
- -0.004709721077233553
- 0.052393000572919846
- 0.026104575023055077
- 0.05130024254322052
- 0.0021716151386499405
- -0.04953917860984802
- -0.030109798535704613
- -0.014168704859912395
- -0.041642867028713226
- 0.011752860620617867
- -0.0015005923341959715
- -0.02828887477517128
- -0.03050399385392666
- 0.0043044788762927055
- 0.012394336052238941
- 0.03279149532318115
- 0.001981662353500724
- 0.047096431255340576
- 0.00881959218531847
- -0.043581005185842514
- 0.0008000566740520298
- -0.010222678072750568
- -0.007957168854773045
- 0.06716743856668472
- 0.00509248860180378
- 0.020392458885908127
- 0.06643788516521454
- -0.009461861103773117
- -0.023267200216650963
- 0.00039855253999121487
- 0.02241506241261959
- -0.031317755579948425
- -0.06490763276815414
- -0.07274720072746277
- 0.0004978705546818674
- -0.07313389331102371
- 0.007188552059233189
- 0.03598335385322571
- -0.014062908478081226
- 0.03652708977460861
- -0.05737607181072235
- -0.015779711306095123
- 0.002503477968275547
- 0.01825254037976265
- -0.03327847644686699
- 0.03507908806204796
- 0.061542410403490067
- 0.015828892588615417
- 0.048780590295791626
- -0.00643352884799242
- 0.09330099821090698
- 0.046297457069158554
- -0.015457688830792904
- -0.014109228737652302
- 0.017946185544133186
- -0.011226577684283257
- -0.05965773016214371
- 0.025642534717917442
- -0.011137092486023903
- 0.010883389972150326
- 0.023802630603313446
- -0.0069578406400978565
- -0.04093053191900253
- 0.05866507813334465
- 0.06505395472049713
- 0.06848663836717606
- -0.07853502035140991
- -0.032755978405475616
- 0.025788577273488045
- -0.09641870111227036
- 0.027463003993034363
- 0.04981214553117752
- 0.034096069633960724
- -0.015044075436890125
- -0.07147958874702454
- 0.019023669883608818
- 0.061958540230989456
- 0.007353935390710831
- 0.012802664190530777
- -0.04427478089928627
- -0.05029236897826195
- 0.07233976572751999
- -0.013883771374821663
- -0.03279373049736023
- -0.028788331896066666
- -0.05145678669214249
- 0.04462249204516411
- -0.011823728680610657
- 0.004037909675389528
- -0.08575967699289322
- 0.0560983344912529
- 0.03167196735739708
- 0.022745275869965553
- -0.04252232611179352
- -0.012893488630652428
- 0.01737191341817379
- 0.0263399388641119
- -0.005754434037953615
- 0.004428426269441843
- 0.005653793457895517
- 0.01242906041443348
- -0.0008232028339989483
- -0.036780450493097305
- -0.07586231082677841
- 0.03669676184654236
- 0.004548933822661638
- 0.08962133526802063
- 0.016183918341994286
- -0.032658763229846954
- -0.037478648126125336
- 0.002384055405855179
- -0.02522870898246765
- 0.02692820504307747
- -0.04586737975478172
- -0.02711409702897072
- 0.006444611120969057
- 0.03899464011192322
- -0.05760804936289787
- -0.19078510999679565
- 0.009657476097345352
- -0.05943167582154274
- -0.033508241176605225
- 0.01812634989619255
- -0.06116142123937607
- 0.08077444136142731
- -0.014692438766360283
- 0.013101747259497643
- 0.024833830073475838
- -0.10425881296396255
- -0.046907659620046616
- -0.03001793660223484
- -0.053107500076293945
- 0.04615218564867973
- 0.003586377017199993
- -0.02759345807135105
- -0.009043593890964985
- -0.02991526760160923
- 0.03837795928120613
- 0.034914735704660416
- 0.0026971164625138044
- -0.04465626925230026
- 0.07466769218444824
- 0.02807849831879139
- 0.012541741132736206
- -0.03508542478084564
- 0.00830760132521391
- 0.06799285113811493
- -0.0655171200633049
- -0.021641751751303673
- 0.04429731145501137
- 0.02198232337832451
- -0.005623462609946728
- 0.006828407756984234
- -0.01975289173424244
- 0.011326245963573456
- -0.024880843237042427
- 0.08901797980070114
- 0.052360739558935165
- -0.0022310700733214617
- -0.008687025867402554
- -0.0005377953639253974
- 0.009973030537366867
- 0.008501224219799042
- -0.011497083120048046
- 0.01120695285499096
- 0.05595841258764267
- -0.03960469365119934
- -0.05474440008401871
- -0.002216997556388378
- 0.08114822953939438
- -0.038984037935733795
- -0.020128298550844193
- 0.01210625097155571
- 0.05086866766214371
- 0.011576186865568161
- -0.05922866240143776
- -0.0202073585242033
- -0.02557891048491001
- 0.024420926347374916
- -0.00838597770780325
- -0.000725594290997833
- 0.03674635291099548
- -0.08074543625116348
- -0.08296841382980347
- -0.005361487623304129
- -0.060489095747470856
- -0.013786102645099163
- -0.011011296883225441
- -0.0023356282617896795
- 0.0017700763419270515
- 0.057241346687078476
- -0.03131807968020439
- -0.05932613089680672
- 0.04572106525301933
- 0.07417093217372894
- 0.0048979101702570915
- -0.06697399914264679
- 0.008861253038048744
- -0.1041555255651474
- -0.0216758381575346
- -0.005855589639395475
- -0.03985041007399559
- -0.028828924521803856
- -0.018156979233026505
- 0.05829492583870888
- 0.012939066626131535
- -0.06706345826387405
- -0.009013740345835686
- 0.012170165777206421
- -0.010557807050645351
- 0.08472394943237305
- -0.005067764315754175
- -0.0804695263504982
- -0.020153751596808434
- 0.08284041285514832
- -0.02594350092113018
- 0.06349745392799377
- 0.018627217039465904
- 0.0626835897564888
- 0.02700476348400116
- 0.01667633280158043
- 0.06558513641357422
- 0.08272014558315277
- 0.06113787367939949
- 0.03149872273206711
- -0.021093592047691345
- -0.010098916478455067
- 0.04116963595151901
- 0.029120249673724174
- 0.05861856788396835
- 0.03214733675122261
- -0.07964063435792923
- 0.004300129599869251
- 0.00017089124594349414
- 0.06095288693904877
- 0.08488059788942337
- 0.02609608694911003
- -0.03441890701651573
- -0.05443834885954857
- 0.06159248203039169
- 0.03935738280415535
- -0.006680320017039776
- 0.010606056079268456
- -0.016778813675045967
- 0.03957061097025871
- 0.004499087575823069
- -0.018989788368344307
- 0.06442811340093613
- 0.05440377816557884
- -0.06507912278175354
- 0.03407900035381317
- 0.04515533894300461
- 0.028161989524960518
- -0.0500120110809803
- 0.04498511180281639
- 0.016702651977539062
- -0.0806228518486023
- -0.0128908921033144
- -0.03529294207692146
- -0.02089248225092888
- 0.051239367574453354
- 0.027548862621188164
- -0.03635600209236145
- 0.04752759635448456
- -0.042514700442552567
- 0.01637893356382847
- 0.04778030514717102
- -0.036849576979875565
- 0.06462399661540985
- -0.028970060870051384
- 0.01794613152742386
- -0.08920709788799286
- -0.007173181511461735
- 0.058956727385520935
- -0.020192712545394897
- 0.06283029168844223
- 0.010672126896679401
- -0.061615172773599625
- 0.015063580125570297
- -0.016063043847680092
- -0.010704517364501953
- -0.03475319221615791
- 0.020509256049990654
- 0.031973160803318024
- 0.027990050613880157
- 0.026292897760868073
- -0.053586654365062714
- 0.011427945457398891
- -0.055549364537000656
- -0.03890172392129898
- 0.04893672093749046
- 0.08178833872079849
- -0.0007959690410643816
- -0.0914197489619255
- -0.01273210346698761
- 0.036081165075302124
- -0.011376959271728992
- -0.060614217072725296
- 0.11123067140579224
- 0.017636267468333244
- -0.06912774592638016
- -0.06728753447532654
- 0.029320651665329933
- 0.052694980055093765
- 0.003035148372873664
- 0.02003546990454197
- 0.019138505682349205
- -0.03426487371325493
- -0.003694196930155158
- -0.049997467547655106
- 0.018438849598169327
- 0.05150943249464035
- 0.015375543385744095
- -0.07540158927440643
- -0.06281400471925735
- 0.050940096378326416
- -0.04447650909423828
- 0.05442088469862938
- -0.022543445229530334
- 0.03795836493372917
- -0.00815608724951744
- 0.011743482202291489
- -0.0174801554530859
- 0.008848908357322216
- -0.029929453507065773
- -0.010430329479277134
- -0.023060502484440804
- 0.09085620194673538
- -0.019465669989585876
- -0.00035748956725001335
- 0.014854228124022484
- -0.041334398090839386
- 0.04200516268610954
- -0.00039908778853714466
- -0.015327595174312592
- -0.13860395550727844
- -0.005371789913624525
- 0.06135489046573639
- 0.0228705033659935
- -0.08226536214351654
- 0.030014390125870705
- -0.06442718952894211
- 0.012735854834318161
- 0.014261633157730103
- -0.0241316519677639
- -0.05506369099020958
- 0.01023655105382204
- 0.009402441792190075
- 0.03946807235479355
- -0.07127946615219116
- 0.02348908595740795
- -0.000785518204793334
- -0.05548502504825592
- -0.06479977071285248
- 0.024784205481410027
- 0.011976197361946106
- 0.012832717970013618
- 0.047236934304237366
- 0.051551997661590576
- -0.006446514278650284
- 0.02958875522017479
- 0.12366349995136261
- -0.013529904186725616
- -0.0331791527569294
- 0.04430180415511131
- 0.05238819867372513
- 0.014311927370727062
- 0.03459496423602104
- 0.03443654254078865
- -0.05471187084913254
- 0.010150739923119545
- 0.02740243822336197
- -0.031848639249801636
- 0.036375973373651505
- -0.0029316579457372427
- 0.01917664147913456
- 0.020023001357913017
- -0.06899929791688919
- -0.035279154777526855
- -0.03230214864015579
- -0.04318904131650925
- 0.05020778626203537
- 0.02122289314866066
- 0.02691306732594967
- -0.08588408678770065
- 0.0035024352837353945
- 0.002811551559716463
- 0.05268246307969093
- 0.13221228122711182
- -0.012371938675642014
- -0.02007283829152584
- -0.01810559257864952
- 0.06343133747577667
- 0.007157924585044384
- 0.016438735648989677
- -0.012568938545882702
- 0.004917947109788656
- 0.06338875740766525
- 0.04792692884802818
- -0.024937359616160393
- 0.06160295009613037
- 0.06473096460103989
- -0.007080894894897938
- -0.0328083373606205
- 0.008332574740052223
- -0.025824956595897675
- -0.004270151257514954
- 0.006285464856773615
- 0.04118054732680321
- 0.027057012543082237
- -0.0726432129740715
- 0.05192961543798447
- -0.05700472742319107
- -0.013085098937153816
- -0.015571258030831814
- 0.025221072137355804
- -0.02122841775417328
- 0.034459199756383896
- 0.056488364934921265
